### ISSUE TITLE
Broken exporter?

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/sentence-collector#193]
```
$ SC_SYSTEM=production yarn run export
yarn run v1.13.0
$ yarn db-helper export
$ yarn build:server && yarn env node dist/db-helper export
$ yarn clean && parcel build -t "node" scripts/db-helper.js
$ rm -rf dist .cache
✨  Built in 7.58s.

dist/db-helper.map    70.34 KB     44ms
dist/db-helper.js     25.96 KB    6.20s
$ env $(grep -v '^#' .env | xargs) node dist/db-helper export
Error: Invalid remote URL: undefined
    at KintoClientBase (/home/nuke/Web/sentence-collector/node_modules/kinto-http/lib/base.js:77:13)
    at new KintoClient (/home/nuke/Web/sentence-collector/node_modules/kinto-http/lib/index.js:33:102)
    at new u (/home/nuke/Web/sentence-collector/dist/db-helper.js:18:573)
    at k (/home/nuke/Web/sentence-collector/dist/db-helper.js:32:753)
    at y (/home/nuke/Web/sentence-collector/dist/db-helper.js:32:1482)
    at Object.parcelRequire.JESa.../shared/db (/home/nuke/Web/sentence-collector/dist/db-helper.js:32:1725)
    at u (/home/nuke/Web/sentence-collector/dist/db-helper.js:1:528)
    at parcelRequire.gZt/ (/home/nuke/Web/sentence-collector/dist/db-helper.js:1:827)
    at Object.<anonymous> (/home/nuke/Web/sentence-collector/dist/db-helper.js:1:1032)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by MichaelKohler** [comment]
Oh right, you want to add the following line to your `.env` file: https://github.com/Common-Voice/sentence-collector/blob/master/.env_template#L6

**Comment by nukeador** [comment]
That was it, thanks!
