### ISSUE TITLE
Sentences export failing

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/sentence-collector#246]
I've just updated from the latest master and now the export process that used to work is not:
```

$ SC_SYSTEM=production npm run export

> sentence-collector@1.12.0 export /home/nuke/Web/sentence-collector
> npm run db-helper export


> sentence-collector@1.12.0 db-helper /home/nuke/Web/sentence-collector
> npm run build:server && npm run env node dist/db-helper "export"


> sentence-collector@1.12.0 build:server /home/nuke/Web/sentence-collector
> npm run clean && parcel build -t "node" scripts/db-helper.js


> sentence-collector@1.12.0 clean /home/nuke/Web/sentence-collector
> rm -rf dist .cache

🚨  /home/nuke/Web/sentence-collector/scripts/db-helper.js: Failed to load plugin react: Cannot find module 'eslint-plugin-react'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.require.resolve (/home/nuke/Web/sentence-collector/node_modules/v8-compile-cache/v8-compile-cache.js:162:23)
    at Plugins.load (/home/nuke/Web/sentence-collector/node_modules/parcel-plugin-eslint/node_modules/eslint/lib/config/plugins.js:106:29)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (/home/nuke/Web/sentence-collector/node_modules/parcel-plugin-eslint/node_modules/eslint/lib/config/plugins.js:166:21)
    at loadFromDisk (/home/nuke/Web/sentence-collector/node_modules/parcel-plugin-eslint/node_modules/eslint/lib/config/config-file.js:501:35)
    at Object.load (/home/nuke/Web/sentence-collector/node_modules/parcel-plugin-eslint/node_modules/eslint/lib/config/config-file.js:559:20)
    at Config.getLocalConfigHierarchy (/home/nuke/Web/sentence-collector/node_modules/parcel-plugin-eslint/node_modules/eslint/lib/config.js:227:44)
    at Config.getConfigHierarchy (/home/nuke/Web/sentence-collector/node_modules/parcel-plugin-eslint/node_modules/eslint/lib/config.js:179:43)
    at Config.getConfigVector (/home/nuke/Web/sentence-collector/node_modules/parcel-plugin-eslint/node_modules/eslint/lib/config.js:286:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sentence-collector@1.12.0 build:server: `npm run clean && parcel build -t "node" scripts/db-helper.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sentence-collector@1.12.0 build:server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nuke/.npm/_logs/2019-07-31T20_46_13_513Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sentence-collector@1.12.0 db-helper: `npm run build:server && npm run env node dist/db-helper "export"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sentence-collector@1.12.0 db-helper script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nuke/.npm/_logs/2019-07-31T20_46_13_528Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sentence-collector@1.12.0 export: `npm run db-helper export`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sentence-collector@1.12.0 export script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nuke/.npm/_logs/2019-07-31T20_46_13_544Z-debug.log

```

**Comment by MichaelKohler** [comment]
`npm ci` installs the latest dependencies. There have been some additions lately.

**Comment by nukeador** [comment]
Emmm, yes. Thanks.
