### ISSUE TITLE
docker-compose up error

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/sentence-collector#5]
After running `docker-compose up`
```
web_1    | Traceback (most recent call last):
web_1    |   File "/usr/local/bin/kinto", line 11, in <module>
web_1    |     load_entry_point('kinto', 'console_scripts', 'kinto')()
web_1    |   File "/app/kinto/__main__.py", line 219, in main
web_1    |     scripts.migrate(env, dry_run=dry_run)
web_1    |   File "/app/kinto/core/scripts.py", line 33, in migrate
web_1    |     getattr(registry, backend).initialize_schema(dry_run=dry_run)
web_1    |   File "/app/kinto/core/storage/postgresql/__init__.py", line 98, in initialize_schema
web_1    |     return self.create_or_migrate_schema(dry_run)
web_1    |   File "/app/kinto/core/storage/postgresql/migrator.py", line 44, in create_or_migrate_schema
web_1    |     version = self.get_installed_version()
web_1    |   File "/app/kinto/core/storage/postgresql/__init__.py", line 178, in get_installed_version
web_1    |     return MAX_FLUSHABLE_SCHEMA_VERSION
web_1    |   File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
web_1    |     self.gen.throw(type, value, traceback)
web_1    |   File "/app/kinto/core/storage/postgresql/client.py", line 63, in connect
web_1    |     raise exceptions.BackendError(original=e) from e
web_1    | kinto.core.storage.exceptions.BackendError: OperationalError: (psycopg2.OperationalError) FATAL:  role "app" does not exist
web_1    |  (Background on this error at: http://sqlalche.me/e/e3q8)
sentencecollector_web_1 exited with code 1
```

**Comment by mikehenrty** [comment]
This might have something to do with the environment file I added. Can you try copying the `.env_template` to `.env` in the root of this project, and running again? Also note I updated the README to include this info.

**Comment by nukeador** [comment]
```
web_1    | Traceback (most recent call last):
web_1    |   File "/usr/local/bin/kinto", line 11, in <module>
web_1    |     load_entry_point('kinto', 'console_scripts', 'kinto')()
web_1    |   File "/app/kinto/__main__.py", line 219, in main
web_1    |     scripts.migrate(env, dry_run=dry_run)
web_1    |   File "/app/kinto/core/scripts.py", line 33, in migrate
web_1    |     getattr(registry, backend).initialize_schema(dry_run=dry_run)
web_1    |   File "/app/kinto/core/storage/postgresql/__init__.py", line 98, in initialize_schema
web_1    |     return self.create_or_migrate_schema(dry_run)
web_1    |   File "/app/kinto/core/storage/postgresql/migrator.py", line 44, in create_or_migrate_schema
web_1    |     version = self.get_installed_version()
web_1    |   File "/app/kinto/core/storage/postgresql/__init__.py", line 178, in get_installed_version
web_1    |     return MAX_FLUSHABLE_SCHEMA_VERSION
web_1    |   File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
web_1    |     self.gen.throw(type, value, traceback)
web_1    |   File "/app/kinto/core/storage/postgresql/client.py", line 63, in connect
web_1    |     raise exceptions.BackendError(original=e) from e
web_1    | kinto.core.storage.exceptions.BackendError: OperationalError: (psycopg2.OperationalError) FATAL:  role "postgres_user" does not exist
web_1    |  (Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by mikehenrty** [comment]
Can you paste the whole output from `docker compose up`?

**Comment by mikehenrty** [comment]
this might be a docker-caching issue after copying the file over. can you do the following:
```
docker-compose rm --f 
docker-compose up
```

then paste the entire output here

**Comment by nukeador** [comment]
OK, it seems now it's up.

http://localhost:8888/v1 returns a json
http://localhost:1234/ is not loading

In which port urls should the site respond?

**Comment by nukeador** [comment]
Just a browser 404

**Comment by nukeador** [comment]
OK, the issue is that once I run docker-composer up I don't get any shell so I assume I have to run yarn from the same folder outside docker but I get:

```
$ yarn
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.
```

**Comment by nukeador** [comment]
Few things:

- I had to install node 10 from snap package
- I had to install curl
- I had to run docker-compose as root or it won't start

Unfortunately I get the same error, from the root directory of the repo

```
nuke@moznuke:~/Web/sentence-collector$ yarn
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.
```

**Comment by nukeador** [comment]
I haven't had time to try again, since other people are able let's close this one and I'll figure out my way if I need to in the future.

**Comment by nukeador** [comment]
> For me it worked as described in the README.
> 
> Installed node 10.13 from deb (on Ubuntu) using
> https://github.com/nodesource/distributions/blob/master/README.md#debinstall
> 
> Your user may have to be added to the docker group in order to avoid running as root.

For reference, this fixed my problem, apparently the packages in the default Ubuntu repos are not working.
